### ISSUE TITLE
Support middleman v4

### ISSUE THREAD

**Issue by alem0lars** [danielbayerlein/middleman-google-analytics#20] opened 2015-03-05 16:17 UTC
At the moment the gem isn't supporting middleman v4 installations.

**Comment by alem0lars** [comment] 2015-04-07 13:13
Do you plan to support newer versions of middleman too?

**Comment by danielbayerlein** [comment] 2015-04-07 15:28
@alem0lars Sorry for the late reply, I have received no notification about it.

Yes, I will support Middleman v4! There is no stable release of Middleman v4, so it can take some time.
PR are welcome :wink:

**Comment by danielbayerlein** [comment] 2015-04-07 16:31
[Upgrading to v4](https://middlemanapp.com/basics/upgrade-v4/)

**Comment by danielbayerlein** [comment] 2015-04-15 17:21
@alem0lars See branch "issue-20".

**Comment by tdreyno** [comment] 2015-09-18 18:36
@danielbayerlein Hey, so I checked out your code... there was a crazy bad issue in cucumber/aruba that was swallowing exceptions and making it appear that failing tests were passing. I'm working through it now and should have an update today. Nice catch!

**Comment by danielbayerlein** [comment] 2015-09-20 08:20
@tdreyno Thanks a lot! Awesome! :clap:

**Comment by tdreyno** [comment] 2015-09-20 21:48
Bug is fixed (though now I have broken tests that I thought were working :disappointed:). Should be good enough for you to resume testing, tho.

**Comment by mojavelinux** [comment] 2015-10-25 22:42
This plugin is attempting to use the `indent` method on a string if minify is not enabled. As far as I can tell, that's not a core Ruby method and causes the plugin to fail. Aside from that, it seems to work just fine with Middleman 4.

**Comment by mojavelinux** [comment] 2015-10-25 23:15
I'm also noticing that the asset_host replacer modifies the GA URL by prepending the host, though this seems more like a bug in the asset_host replacer. I'm getting something like:

```
/folder//www.google-analytics.com/analytics.js
```

assuming the config is:


```
activate :asset_host, host: '/folder', sources: %w(.html)
```

**Comment by tdreyno** [comment] 2015-10-26 02:02
That does look like a bug in `asset_host` for v4.

**Comment by mojavelinux** [comment] 2015-10-26 03:44
@tdreyno I'll try to dig up more details and report it in the proper place. I just wanted to mention it so others know to watch out for it in the meantime. I was able to work around it temporarily using the following hack:

```
= google_analytics_universal_tag.sub(/"(\/\/.*?)"/, '"http:\1".substr(5)')
```

**Comment by danielbayerlein** [comment] 2015-10-26 18:03
@mojavelinux Thank your for your feedback.

**Comment by mojavelinux** [comment] 2015-10-26 21:28
Btw, filed an issue here and @tdreyno merged it: https://github.com/middleman/middleman/pull/1655

In the meantime, another way to solve the problem is to use a host proc:

```ruby
activate :asset_host, host: Proc.new {|asset|
  asset.start_with?('//') ? '' : '<path or absolute URL>'
}
```

**Comment by danielbayerlein** [comment] 2015-12-16 19:33
middleman-google-analytics v2.0.0 released. :v:

**Closed by danielbayerlein** 2015-12-16 19:33 UTC

**Comment by mojavelinux** [comment] 2015-12-16 20:00
Solid!

**Comment by alem0lars** [comment] 2015-12-17 08:06
nice!
